### ISSUE TITLE
Turn expire trait from date-based to state-based

### ISSUE THREAD

**Issue by badboy** [fiji-flo/shared-expiry-get#1]
```rust
trait Expiry {
  fn is_expired() -> bool;
}
```

Return true if the resource is expired. That allows the implementor to decide how to expire (based on time, a counter, external triggers, ...)
will also make the tests less brittle as you can base them on the counter.

**Comment by fiji-flo** [comment]
I went with `fn vaild() -> bool`. Thanks for the feedback.
